export type StudentStage = "Early Builder" | "Pre-Applicant" | "Active Applicant";
export type AcademicStrengthBand = "Developing" | "Moderate" | "Strong" | "Very Strong";
export type TestReadinessBand = "Not Started" | "In Progress" | "Competitive" | "Highly Competitive";
export type ScholarshipDependence = "Low" | "Medium" | "High";
export type AffordabilitySensitivity = "Flexible" | "Moderate" | "Sensitive" | "Highly Sensitive";

export type RecommendationTier = "Reach" | "Target" | "Safety";
export type ConfidenceLevel = "Low" | "Medium" | "High";
export type BudgetFit = "Within Budget" | "Stretch" | "Over Budget";
export type DeadlinePressure = "Low" | "Medium" | "High";

export interface SchoolRecommendation {
  schoolName: string;
  city: string;
  state: string;
  tuitionAnnualUsd: number;
  estimatedCostOfAttendanceUsd: number;
  scholarshipAvailabilityFlag: boolean;
  scholarshipNotes?: string;
  lastVerifiedAt: string;
  sourceUrls: string[];
  tier: RecommendationTier;
  currentOutlook: string;
  projectedOutlook: string;
  confidenceLevel: ConfidenceLevel;
  budgetFit: BudgetFit;
  deadlinePressure: DeadlinePressure;
  reasonsForFit: string[];
  topBlockers: string[];
  nextActions: string[];
}

export interface StudentProfile {
  id: string;
  name: string;
  email: string;
  phone: string;
  gradeLevel: number;
  graduationYear: number;
  curriculum: string;
  gpa: string;
  gradeTrend: "Upward" | "Stable" | "Downward";
  intendedMajors: string[];
  highSchool: string;
  testScores: {
    ielts?: string;
    toefl?: string;
    sat?: string;
    act?: string;
  };
  activities: string;
  awards: string;
  leadership: string;
  volunteering: string;
  projects: string;
  essayStatus: string;
  recommendationLetters: string;
  documentStatus: string;
  geographicPreferences: string[];
  campusType: string;
  campusSize: string;
  targetAnnualBudget: string;
  maxStretchBudget: string;
  scholarshipNeed: "None" | "Low" | "Medium" | "High" | "Critical";
  strategyMode: string;
  studentStage: StudentStage;
  academicStrengthBand: AcademicStrengthBand;
  testReadinessBand: TestReadinessBand;
  activityDepthSignal: string;
  leadershipSignal: string;
  scholarshipDependence: ScholarshipDependence;
  affordabilitySensitivity: AffordabilitySensitivity;
  handoffDate: string;
  chatSummary: string;
  bookingIntent?: {
    topic: string;
    timeWindow: string;
    status: "pending" | "confirmed" | "completed";
  };
  recommendations: {
    reach: SchoolRecommendation[];
    target: SchoolRecommendation[];
    safety: SchoolRecommendation[];
  };
}

export const dashboardTheme = {
  background: "#F8FAFC",
  card: "#FFFFFF",
  navy: "#0A2240",
  navyTint: "#123560",
  orange: "#F37021",
  border: "#E2E8F0",
  muted: "#64748B",
  foreground: "#0F172A",
  surfaceSoft: "#F1F5F9",
  surfaceStrong: "#E2E8F0",
  success: "#16A34A",
  successSoft: "#DCFCE7",
  warning: "#D97706",
  warningSoft: "#FEF3C7",
  info: "#2563EB",
  infoSoft: "#DBEAFE",
  destructive: "#DC2626",
  destructiveSoft: "#FEE2E2",
  reach: "#EAB308",
  target: "#38BDF8",
  safety: "#22C55E",
  scholarship: "#D1FAE5",
  deadline: "#FEF3C7",
};

export const students: StudentProfile[] = [
  {
    id: "1",
    name: "Nguyen Minh Anh",
    email: "minhanh.nguyen@gmail.com",
    phone: "+84 912 345 678",
    gradeLevel: 11,
    graduationYear: 2027,
    curriculum: "Vietnamese National + AP",
    gpa: "3.87 / 4.0",
    gradeTrend: "Upward",
    intendedMajors: ["Computer Science", "Data Science"],
    highSchool: "Hanoi-Amsterdam High School",
    testScores: { ielts: "7.5", sat: "1480" },
    activities: "Founded coding club, hackathon organizer, robotics team captain, competitive programming",
    awards: "National Informatics Olympiad Bronze, Hackathon Vietnam Top 10",
    leadership: "President of STEM Club, Volunteer coordinator at local NGO",
    volunteering: "Tech literacy program for underprivileged students (100+ hrs)",
    projects: "AI-powered study planner app, open-source contributions",
    essayStatus: "Draft 1 complete for Common App personal statement",
    recommendationLetters: "2 secured (CS teacher, club advisor)",
    documentStatus: "Transcript ready, financial documents in progress",
    geographicPreferences: ["Northeast US", "California"],
    campusType: "Urban",
    campusSize: "Large",
    targetAnnualBudget: "$45,000",
    maxStretchBudget: "$55,000",
    scholarshipNeed: "Medium",
    strategyMode: "Balanced - mix of ED and RD",
    studentStage: "Active Applicant",
    academicStrengthBand: "Strong",
    testReadinessBand: "Competitive",
    activityDepthSignal: "Strong - multiple sustained commitments with measurable impact",
    leadershipSignal: "Strong - leadership in 3+ organizations with clear initiative",
    scholarshipDependence: "Medium",
    affordabilitySensitivity: "Moderate",
    handoffDate: "2026-03-18",
    chatSummary:
      "Student is highly motivated and focused on CS programs with strong research opportunities. Primary concern is balancing reach schools with financial safety nets. Interested in co-op and internship programs.",
    bookingIntent: {
      topic: "ED strategy and school list finalization",
      timeWindow: "March 22-25, Morning preferred",
      status: "pending",
    },
    recommendations: {
      reach: [
        {
          schoolName: "MIT",
          city: "Cambridge",
          state: "MA",
          tuitionAnnualUsd: 61990,
          estimatedCostOfAttendanceUsd: 85960,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Need-based aid meets 100% demonstrated need",
          lastVerifiedAt: "2026-02-15",
          sourceUrls: ["https://sfs.mit.edu/undergraduate-students/the-cost-of-attendance/"],
          tier: "Reach",
          currentOutlook: "Competitive",
          projectedOutlook: "Strong if SAT improves to 1520+",
          confidenceLevel: "Medium",
          budgetFit: "Stretch",
          deadlinePressure: "High",
          reasonsForFit: ["Strong CS extracurriculars align with MIT culture", "Olympiad background shows problem solving", "Upward GPA trend"],
          topBlockers: ["SAT score slightly below median", "Need stronger research narrative in essays"],
          nextActions: ["Retake SAT targeting 1520+", "Develop research story for personal statement", "Identify MIT-specific programs to reference"],
        },
        {
          schoolName: "Stanford University",
          city: "Stanford",
          state: "CA",
          tuitionAnnualUsd: 62484,
          estimatedCostOfAttendanceUsd: 87225,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Need-blind admissions, meets full demonstrated need",
          lastVerifiedAt: "2026-02-10",
          sourceUrls: ["https://financialaid.stanford.edu/undergrad/budget/"],
          tier: "Reach",
          currentOutlook: "Competitive",
          projectedOutlook: "Moderate - essay differentiation critical",
          confidenceLevel: "Low",
          budgetFit: "Stretch",
          deadlinePressure: "Medium",
          reasonsForFit: ["Entrepreneurial projects align with Stanford culture", "Strong CS + Data Science combo"],
          topBlockers: ["Extremely low acceptance rate", "Need unique personal narrative"],
          nextActions: ["Craft Stanford-specific supplemental essays", "Highlight entrepreneurial impact in app project"],
        },
      ],
      target: [
        {
          schoolName: "Georgia Tech",
          city: "Atlanta",
          state: "GA",
          tuitionAnnualUsd: 33794,
          estimatedCostOfAttendanceUsd: 53496,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Merit scholarships available for international students",
          lastVerifiedAt: "2026-03-01",
          sourceUrls: ["https://finaid.gatech.edu/costs/cost-attendance"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Very Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Strong CS program", "Robotics and hackathon experience are a fit", "Co-op program aligns with interest"],
          topBlockers: [],
          nextActions: ["Apply EA for best chances", "Research co-op program details for essay"],
        },
        {
          schoolName: "University of Michigan",
          city: "Ann Arbor",
          state: "MI",
          tuitionAnnualUsd: 57590,
          estimatedCostOfAttendanceUsd: 76000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Limited merit aid for OOS/international",
          lastVerifiedAt: "2026-02-20",
          sourceUrls: ["https://finaid.umich.edu/cost-of-attendance/"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Strong",
          confidenceLevel: "Medium",
          budgetFit: "Over Budget",
          deadlinePressure: "Medium",
          reasonsForFit: ["Top CS program with research opportunities", "Strong Vietnamese student community"],
          topBlockers: ["OOS tuition exceeds max stretch budget", "Limited merit scholarships"],
          nextActions: ["Evaluate financial fit carefully", "Apply for departmental scholarships"],
        },
        {
          schoolName: "UIUC",
          city: "Champaign",
          state: "IL",
          tuitionAnnualUsd: 38710,
          estimatedCostOfAttendanceUsd: 56000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "CS department scholarships available",
          lastVerifiedAt: "2026-03-05",
          sourceUrls: ["https://cs.illinois.edu/admissions/undergraduate"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Strong",
          confidenceLevel: "High",
          budgetFit: "Stretch",
          deadlinePressure: "Low",
          reasonsForFit: ["Top CS program", "Strong competitive programming culture"],
          topBlockers: ["CS direct admit is competitive"],
          nextActions: ["Apply early for direct CS admission", "Highlight competitive programming achievements"],
        },
      ],
      safety: [
        {
          schoolName: "Arizona State University",
          city: "Tempe",
          state: "AZ",
          tuitionAnnualUsd: 32076,
          estimatedCostOfAttendanceUsd: 48000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Generous merit aid for international students with strong academics",
          lastVerifiedAt: "2026-03-10",
          sourceUrls: ["https://students.asu.edu/international/costs"],
          tier: "Safety",
          currentOutlook: "Very Strong",
          projectedOutlook: "Very Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["High acceptance rate with merit aid", "Growing CS program", "Strong career services"],
          topBlockers: [],
          nextActions: ["Submit application for automatic merit scholarship consideration"],
        },
        {
          schoolName: "University of Utah",
          city: "Salt Lake City",
          state: "UT",
          tuitionAnnualUsd: 30060,
          estimatedCostOfAttendanceUsd: 44000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "International merit scholarships up to $15,000/year",
          lastVerifiedAt: "2026-03-10",
          sourceUrls: ["https://admissions.utah.edu/cost-aid/"],
          tier: "Safety",
          currentOutlook: "Very Strong",
          projectedOutlook: "Very Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Strong gaming and entertainment computing program", "Good scholarship availability", "Affordable COA"],
          topBlockers: [],
          nextActions: ["Apply for departmental scholarship by priority deadline"],
        },
      ],
    },
  },
  {
    id: "2",
    name: "Tran Bao Ngoc",
    email: "bngoc.tran@outlook.com",
    phone: "+84 903 456 789",
    gradeLevel: 12,
    graduationYear: 2026,
    curriculum: "IB Diploma",
    gpa: "3.72 / 4.0",
    gradeTrend: "Stable",
    intendedMajors: ["Business Administration", "Finance"],
    highSchool: "Le Hong Phong HCMC",
    testScores: { toefl: "105", sat: "1420" },
    activities: "Business competition finalist, school newspaper editor-in-chief, student council treasurer",
    awards: "FBLA National Finalist, Best Delegate at HCMC MUN",
    leadership: "VP of Entrepreneurship Club, Student Council Treasurer",
    volunteering: "Financial literacy workshops for local communities (80+ hrs)",
    projects: "Micro-investment platform prototype",
    essayStatus: "Final draft under review",
    recommendationLetters: "3 secured (IB coordinator, economics teacher, club advisor)",
    documentStatus: "All documents submitted",
    geographicPreferences: ["Northeast US", "Midwest"],
    campusType: "Urban",
    campusSize: "Large",
    targetAnnualBudget: "$50,000",
    maxStretchBudget: "$60,000",
    scholarshipNeed: "Low",
    strategyMode: "Aggressive - ED2 focus",
    studentStage: "Active Applicant",
    academicStrengthBand: "Strong",
    testReadinessBand: "Competitive",
    activityDepthSignal: "Moderate - broad profile with business focus",
    leadershipSignal: "Moderate - VP and treasurer roles show initiative",
    scholarshipDependence: "Low",
    affordabilitySensitivity: "Flexible",
    handoffDate: "2026-03-17",
    chatSummary: "Student is anxious about upcoming deadlines for round 2 applications. Wants confirmation on school list and final essay review. Parents are supportive of budget.",
    bookingIntent: {
      topic: "Urgent deadline review - RD applications due in 2 weeks",
      timeWindow: "ASAP - next 48 hours",
      status: "pending",
    },
    recommendations: {
      reach: [
        {
          schoolName: "NYU Stern",
          city: "New York",
          state: "NY",
          tuitionAnnualUsd: 62192,
          estimatedCostOfAttendanceUsd: 88000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Merit scholarships for top applicants",
          lastVerifiedAt: "2026-02-28",
          sourceUrls: ["https://www.nyu.edu/admissions/financial-aid-and-scholarships.html"],
          tier: "Reach",
          currentOutlook: "Competitive",
          projectedOutlook: "Moderate - strong Why NYU essay needed",
          confidenceLevel: "Medium",
          budgetFit: "Over Budget",
          deadlinePressure: "High",
          reasonsForFit: ["Strong business program in global financial capital", "IB background valued"],
          topBlockers: ["Need to finalize Why NYU essay", "COA exceeds max budget without scholarship"],
          nextActions: ["Finalize supplemental essays ASAP", "Apply for Stern scholarship"],
        },
      ],
      target: [
        {
          schoolName: "Boston University",
          city: "Boston",
          state: "MA",
          tuitionAnnualUsd: 65168,
          estimatedCostOfAttendanceUsd: 86000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Trustee and Presidential scholarships",
          lastVerifiedAt: "2026-03-01",
          sourceUrls: ["https://www.bu.edu/admissions/tuition-aid/"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Strong",
          confidenceLevel: "High",
          budgetFit: "Stretch",
          deadlinePressure: "High",
          reasonsForFit: ["Strong Questrom business school", "Urban campus matches preference", "IB-friendly"],
          topBlockers: [],
          nextActions: ["Submit RD application before deadline", "Apply for merit scholarships"],
        },
        {
          schoolName: "UW-Madison",
          city: "Madison",
          state: "WI",
          tuitionAnnualUsd: 40603,
          estimatedCostOfAttendanceUsd: 58000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "International merit scholarships available",
          lastVerifiedAt: "2026-03-05",
          sourceUrls: ["https://financialaid.wisc.edu/cost-of-attendance/"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Medium",
          reasonsForFit: ["Strong business school", "Good international student support"],
          topBlockers: [],
          nextActions: ["Submit application", "Research Wisconsin School of Business honors program"],
        },
      ],
      safety: [
        {
          schoolName: "Indiana University Kelley",
          city: "Bloomington",
          state: "IN",
          tuitionAnnualUsd: 40482,
          estimatedCostOfAttendanceUsd: 55000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Automatic merit aid for qualifying students",
          lastVerifiedAt: "2026-03-08",
          sourceUrls: ["https://admissions.indiana.edu/cost-financial-aid/"],
          tier: "Safety",
          currentOutlook: "Very Strong",
          projectedOutlook: "Very Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Top-ranked undergraduate business program", "Strong placement rates", "Affordable"],
          topBlockers: [],
          nextActions: ["Apply for direct admit to Kelley School"],
        },
      ],
    },
  },
  {
    id: "3",
    name: "Le Hoang Khoi",
    email: "khoi.le@gmail.com",
    phone: "+84 987 654 321",
    gradeLevel: 10,
    graduationYear: 2028,
    curriculum: "Vietnamese National",
    gpa: "3.91 / 4.0",
    gradeTrend: "Upward",
    intendedMajors: ["Biomedical Engineering"],
    highSchool: "Phan Boi Chau Gifted School",
    testScores: { ielts: "6.5" },
    activities: "Science olympiad participant, biology lab assistant",
    awards: "Provincial Biology Olympiad Silver",
    leadership: "Class representative, peer tutor in biology",
    volunteering: "Hospital volunteer (60+ hrs), health education outreach",
    projects: "Water quality testing project for local community",
    essayStatus: "Not started",
    recommendationLetters: "None secured yet",
    documentStatus: "Transcript available",
    geographicPreferences: ["Northeast US", "Southeast US"],
    campusType: "Suburban",
    campusSize: "Medium",
    targetAnnualBudget: "$35,000",
    maxStretchBudget: "$40,000",
    scholarshipNeed: "High",
    strategyMode: "Conservative - building profile first",
    studentStage: "Early Builder",
    academicStrengthBand: "Very Strong",
    testReadinessBand: "In Progress",
    activityDepthSignal: "Developing - good foundation but needs sustained commitment",
    leadershipSignal: "Emerging - class-level roles, needs broader impact",
    scholarshipDependence: "High",
    affordabilitySensitivity: "Highly Sensitive",
    handoffDate: "2026-03-15",
    chatSummary: "Student is in early exploration phase. Interested in biomedical engineering but also curious about pre-med tracks. Needs guidance on extracurricular profile and English proficiency.",
    recommendations: {
      reach: [
        {
          schoolName: "Johns Hopkins University",
          city: "Baltimore",
          state: "MD",
          tuitionAnnualUsd: 63340,
          estimatedCostOfAttendanceUsd: 84000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Need-blind, meets full demonstrated need",
          lastVerifiedAt: "2026-02-20",
          sourceUrls: ["https://finaid.jhu.edu/"],
          tier: "Reach",
          currentOutlook: "Too Early to Assess",
          projectedOutlook: "Possible with strong trajectory over 2 years",
          confidenceLevel: "Low",
          budgetFit: "Over Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["World-leading BME program", "Research culture matches student interest"],
          topBlockers: ["IELTS needs significant improvement", "Need substantial research experience", "No SAT score yet"],
          nextActions: ["Focus on IELTS preparation", "Seek research mentorship", "Begin SAT preparation"],
        },
      ],
      target: [
        {
          schoolName: "Case Western Reserve",
          city: "Cleveland",
          state: "OH",
          tuitionAnnualUsd: 58204,
          estimatedCostOfAttendanceUsd: 75000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Merit scholarships up to full tuition",
          lastVerifiedAt: "2026-02-25",
          sourceUrls: ["https://case.edu/admission/tuition-aid"],
          tier: "Target",
          currentOutlook: "Too Early to Assess",
          projectedOutlook: "Good potential with profile development",
          confidenceLevel: "Low",
          budgetFit: "Over Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Strong BME program", "Good scholarship opportunities"],
          topBlockers: ["Build clinical and research experience", "Improve English proficiency"],
          nextActions: ["Research summer programs at CWRU", "Build portfolio of science projects"],
        },
      ],
      safety: [
        {
          schoolName: "University of Arizona",
          city: "Tucson",
          state: "AZ",
          tuitionAnnualUsd: 29030,
          estimatedCostOfAttendanceUsd: 42000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Generous international merit aid",
          lastVerifiedAt: "2026-03-10",
          sourceUrls: ["https://financialaid.arizona.edu/types-of-aid/scholarships"],
          tier: "Safety",
          currentOutlook: "Too Early to Assess",
          projectedOutlook: "Strong potential",
          confidenceLevel: "Medium",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Growing BME program", "Affordable with merit aid", "Supportive international community"],
          topBlockers: [],
          nextActions: ["Monitor program developments", "Apply for Wildcat Excellence Award when eligible"],
        },
      ],
    },
  },
  {
    id: "4",
    name: "Pham Thu Ha",
    email: "thuha.pham@yahoo.com",
    phone: "+84 976 543 210",
    gradeLevel: 11,
    graduationYear: 2027,
    curriculum: "Vietnamese National + Cambridge IGCSE",
    gpa: "3.65 / 4.0",
    gradeTrend: "Stable",
    intendedMajors: ["Psychology", "Cognitive Science"],
    highSchool: "Chu Van An High School",
    testScores: { ielts: "7.0" },
    activities: "Mental health awareness club founder, peer counselor, debate team, psychology reading group",
    awards: "National Debate Tournament Top 20, School Psychology Essay Prize",
    leadership: "Founded school's first mental health club, debate team captain",
    volunteering: "Peer counseling hotline volunteer (120+ hrs), youth mental health NGO",
    projects: "Mental health awareness campaign reaching 1,000+ students",
    essayStatus: "Brainstorming phase - strong personal narrative identified",
    recommendationLetters: "1 secured (debate coach), need 1 more",
    documentStatus: "Transcript available, need to request IGCSE certificates",
    geographicPreferences: ["California", "Pacific Northwest"],
    campusType: "Urban or Suburban",
    campusSize: "Medium to Large",
    targetAnnualBudget: "$40,000",
    maxStretchBudget: "$48,000",
    scholarshipNeed: "High",
    strategyMode: "Balanced - targeting merit scholarships",
    studentStage: "Pre-Applicant",
    academicStrengthBand: "Moderate",
    testReadinessBand: "Competitive",
    activityDepthSignal: "Strong - deep commitment to mental health advocacy with measurable reach",
    leadershipSignal: "Strong - founder role with clear community impact",
    scholarshipDependence: "High",
    affordabilitySensitivity: "Sensitive",
    handoffDate: "2026-03-19",
    chatSummary: "Student has a compelling personal story related to mental health advocacy. Needs help identifying psychology programs with strong clinical training components.",
    recommendations: {
      reach: [
        {
          schoolName: "UCLA",
          city: "Los Angeles",
          state: "CA",
          tuitionAnnualUsd: 46326,
          estimatedCostOfAttendanceUsd: 70000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Limited merit aid for OOS/international",
          lastVerifiedAt: "2026-02-28",
          sourceUrls: ["https://admission.ucla.edu/tuition-aid"],
          tier: "Reach",
          currentOutlook: "Competitive",
          projectedOutlook: "Moderate - strong fit with advocacy narrative",
          confidenceLevel: "Medium",
          budgetFit: "Over Budget",
          deadlinePressure: "Medium",
          reasonsForFit: ["Top psychology program", "Location matches preference", "Strong research opportunities"],
          topBlockers: ["GPA below median", "Limited financial aid"],
          nextActions: ["Strengthen GPA", "Consider SAT to boost competitiveness", "Develop UCLA-specific essay"],
        },
      ],
      target: [
        {
          schoolName: "University of Washington",
          city: "Seattle",
          state: "WA",
          tuitionAnnualUsd: 42099,
          estimatedCostOfAttendanceUsd: 58000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Some merit scholarships for international students",
          lastVerifiedAt: "2026-03-01",
          sourceUrls: ["https://admit.washington.edu/costs/cost-of-attendance/"],
          tier: "Target",
          currentOutlook: "Moderate",
          projectedOutlook: "Good with improved test scores",
          confidenceLevel: "Medium",
          budgetFit: "Stretch",
          deadlinePressure: "Medium",
          reasonsForFit: ["Strong psychology department", "Pacific Northwest location matches preference"],
          topBlockers: ["Need to strengthen standardized test profile"],
          nextActions: ["Consider taking SAT", "Research UW psychology honors program"],
        },
        {
          schoolName: "University of Oregon",
          city: "Eugene",
          state: "OR",
          tuitionAnnualUsd: 39897,
          estimatedCostOfAttendanceUsd: 52000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "ICSP scholarships up to $36,000/year",
          lastVerifiedAt: "2026-03-05",
          sourceUrls: ["https://admissions.uoregon.edu/icsp"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Good psychology program", "Scholarship opportunities bring within budget", "PNW location"],
          topBlockers: [],
          nextActions: ["Apply for ICSP scholarship early", "Research clinical psychology track"],
        },
      ],
      safety: [
        {
          schoolName: "Oregon State University",
          city: "Corvallis",
          state: "OR",
          tuitionAnnualUsd: 33012,
          estimatedCostOfAttendanceUsd: 46000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Provost's Excellence Award for international students",
          lastVerifiedAt: "2026-03-08",
          sourceUrls: ["https://admissions.oregonstate.edu/international-scholarships"],
          tier: "Safety",
          currentOutlook: "Strong",
          projectedOutlook: "Very Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Affordable with scholarships", "Good psychology program", "Supportive international community"],
          topBlockers: [],
          nextActions: ["Apply for Provost's Excellence Award", "Submit application early"],
        },
      ],
    },
  },
  {
    id: "5",
    name: "Vo Duc Thinh",
    email: "thinh.vo@gmail.com",
    phone: "+84 938 765 432",
    gradeLevel: 11,
    graduationYear: 2027,
    curriculum: "British International (A-Levels)",
    gpa: "3.78 / 4.0",
    gradeTrend: "Upward",
    intendedMajors: ["Mechanical Engineering"],
    highSchool: "BVIS Ho Chi Minh City",
    testScores: { ielts: "7.5", sat: "1450" },
    activities: "Robotics competition finalist, 3D printing club, engineering internship",
    awards: "National Robotics Competition Finalist, STEM Innovation Prize",
    leadership: "Robotics team lead, community makerspace mentor",
    volunteering: "Makerspace mentor for middle school students (90+ hrs)",
    projects: "Designed and 3D-printed prosthetic hand prototype, automated greenhouse system",
    essayStatus: "Outline ready - focusing on prosthetic hand project narrative",
    recommendationLetters: "1 secured (physics teacher), 1 pending (internship supervisor)",
    documentStatus: "Transcript and A-Level predictions available",
    geographicPreferences: ["Midwest", "Northeast US"],
    campusType: "Suburban or College Town",
    campusSize: "Large",
    targetAnnualBudget: "$55,000",
    maxStretchBudget: "$65,000",
    scholarshipNeed: "Low",
    strategyMode: "Balanced - EA where possible",
    studentStage: "Pre-Applicant",
    academicStrengthBand: "Strong",
    testReadinessBand: "Competitive",
    activityDepthSignal: "Strong - hands-on engineering with real-world applications",
    leadershipSignal: "Moderate - team lead and mentoring roles",
    scholarshipDependence: "Low",
    affordabilitySensitivity: "Flexible",
    handoffDate: "2026-03-20",
    chatSummary: "Student has strong hands-on engineering experience with real-world impact projects. Looking for programs with project-based learning and industry connections.",
    recommendations: {
      reach: [
        {
          schoolName: "Purdue University",
          city: "West Lafayette",
          state: "IN",
          tuitionAnnualUsd: 31104,
          estimatedCostOfAttendanceUsd: 47000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Engineering scholarships available",
          lastVerifiedAt: "2026-03-01",
          sourceUrls: ["https://www.purdue.edu/provost/students/s-financialaid/Cost-of-Attendance.html"],
          tier: "Reach",
          currentOutlook: "Good",
          projectedOutlook: "Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Medium",
          reasonsForFit: ["Top-ranked ME program", "Strong industry connections", "Co-op opportunities"],
          topBlockers: ["Competitive ME admission for international students"],
          nextActions: ["Apply EA", "Highlight prosthetic hand project in application"],
        },
      ],
      target: [
        {
          schoolName: "University of Michigan",
          city: "Ann Arbor",
          state: "MI",
          tuitionAnnualUsd: 57590,
          estimatedCostOfAttendanceUsd: 76000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Limited merit for international",
          lastVerifiedAt: "2026-02-20",
          sourceUrls: ["https://finaid.umich.edu/cost-of-attendance/"],
          tier: "Target",
          currentOutlook: "Moderate",
          projectedOutlook: "Good with strong essays",
          confidenceLevel: "Medium",
          budgetFit: "Stretch",
          deadlinePressure: "Medium",
          reasonsForFit: ["Top ME program", "Strong project-based curriculum"],
          topBlockers: ["Competitive engineering admit", "Tuition near max budget"],
          nextActions: ["Secure internship supervisor recommendation", "Develop Michigan-specific engineering essay"],
        },
        {
          schoolName: "Virginia Tech",
          city: "Blacksburg",
          state: "VA",
          tuitionAnnualUsd: 36090,
          estimatedCostOfAttendanceUsd: 52000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Engineering merit scholarships",
          lastVerifiedAt: "2026-03-05",
          sourceUrls: ["https://www.vt.edu/admissions/tuition.html"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Excellent hands-on engineering culture", "Strong ME program", "Affordable"],
          topBlockers: [],
          nextActions: ["Apply EA for priority consideration"],
        },
      ],
      safety: [
        {
          schoolName: "Iowa State University",
          city: "Ames",
          state: "IA",
          tuitionAnnualUsd: 26152,
          estimatedCostOfAttendanceUsd: 40000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Automatic merit scholarships based on GPA/test scores",
          lastVerifiedAt: "2026-03-10",
          sourceUrls: ["https://www.admissions.iastate.edu/cost/"],
          tier: "Safety",
          currentOutlook: "Very Strong",
          projectedOutlook: "Very Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Strong ME program", "Excellent co-op opportunities", "Very affordable"],
          topBlockers: [],
          nextActions: ["Submit application for automatic scholarship consideration"],
        },
      ],
    },
  },
  {
    id: "6",
    name: "Dang Quynh Anh",
    email: "quynhanh.dang@gmail.com",
    phone: "+84 901 234 567",
    gradeLevel: 12,
    graduationYear: 2026,
    curriculum: "Vietnamese National + AP",
    gpa: "3.82 / 4.0",
    gradeTrend: "Upward",
    intendedMajors: ["International Relations", "Political Science"],
    highSchool: "Nguyen Hue High School",
    testScores: { toefl: "110", sat: "1460" },
    activities: "Model UN delegate, student ambassador, policy research intern at think tank",
    awards: "Best Delegate at ASEAN MUN, National Essay Competition Winner",
    leadership: "Secretary General of school MUN, Youth Advisory Board member",
    volunteering: "Youth policy advocacy group (150+ hrs), election monitoring volunteer",
    projects: "Policy brief on Vietnam-US educational exchange published in school journal",
    essayStatus: "Final drafts complete for all target schools",
    recommendationLetters: "3 secured (AP History teacher, MUN advisor, internship supervisor)",
    documentStatus: "All documents ready and submitted",
    geographicPreferences: ["Washington DC area", "Northeast US"],
    campusType: "Urban",
    campusSize: "Medium",
    targetAnnualBudget: "$48,000",
    maxStretchBudget: "$55,000",
    scholarshipNeed: "Medium",
    strategyMode: "Aggressive - considering ED2",
    studentStage: "Active Applicant",
    academicStrengthBand: "Strong",
    testReadinessBand: "Highly Competitive",
    activityDepthSignal: "Very Strong - deep policy and IR involvement with real-world experience",
    leadershipSignal: "Very Strong - Secretary General role and city-level advisory position",
    scholarshipDependence: "Medium",
    affordabilitySensitivity: "Moderate",
    handoffDate: "2026-03-16",
    chatSummary: "Student has strong IR profile with real policy experience. Finalizing school list and needs guidance on ED2 vs RD strategy.",
    bookingIntent: {
      topic: "ED2 strategy discussion - Georgetown vs GWU decision",
      timeWindow: "March 21, Afternoon",
      status: "pending",
    },
    recommendations: {
      reach: [
        {
          schoolName: "Georgetown University",
          city: "Washington",
          state: "DC",
          tuitionAnnualUsd: 65082,
          estimatedCostOfAttendanceUsd: 87000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Need-based aid available, no merit scholarships",
          lastVerifiedAt: "2026-02-15",
          sourceUrls: ["https://finaid.georgetown.edu/"],
          tier: "Reach",
          currentOutlook: "Competitive",
          projectedOutlook: "Moderate-Strong - SFS is highly selective",
          confidenceLevel: "Medium",
          budgetFit: "Over Budget",
          deadlinePressure: "High",
          reasonsForFit: ["Premier IR program", "DC location ideal for internships", "MUN and policy experience align perfectly"],
          topBlockers: ["Highly selective program", "COA exceeds budget without significant aid"],
          nextActions: ["Decide on ED2 by deadline", "Ensure financial aid application is complete", "Polish Georgetown-specific essays"],
        },
      ],
      target: [
        {
          schoolName: "George Washington University",
          city: "Washington",
          state: "DC",
          tuitionAnnualUsd: 63830,
          estimatedCostOfAttendanceUsd: 82000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Presidential and merit scholarships up to full tuition",
          lastVerifiedAt: "2026-03-01",
          sourceUrls: ["https://financialaid.gwu.edu/"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Strong - merit scholarship likely",
          confidenceLevel: "High",
          budgetFit: "Stretch",
          deadlinePressure: "High",
          reasonsForFit: ["Strong Elliott School of IR", "DC location", "Good merit scholarship chances"],
          topBlockers: [],
          nextActions: ["Submit RD application", "Apply for Presidential scholarship"],
        },
        {
          schoolName: "American University",
          city: "Washington",
          state: "DC",
          tuitionAnnualUsd: 56730,
          estimatedCostOfAttendanceUsd: 74000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "Generous merit aid for international students",
          lastVerifiedAt: "2026-03-05",
          sourceUrls: ["https://www.american.edu/financialaid/"],
          tier: "Target",
          currentOutlook: "Good",
          projectedOutlook: "Very Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Medium",
          reasonsForFit: ["Strong IR program", "DC location", "Excellent scholarship opportunities", "Strong internship placement"],
          topBlockers: [],
          nextActions: ["Apply for AU Emerging Global Leader scholarship"],
        },
      ],
      safety: [
        {
          schoolName: "University of Maryland",
          city: "College Park",
          state: "MD",
          tuitionAnnualUsd: 40306,
          estimatedCostOfAttendanceUsd: 56000,
          scholarshipAvailabilityFlag: true,
          scholarshipNotes: "International merit scholarships available",
          lastVerifiedAt: "2026-03-08",
          sourceUrls: ["https://financialaid.umd.edu/"],
          tier: "Safety",
          currentOutlook: "Strong",
          projectedOutlook: "Very Strong",
          confidenceLevel: "High",
          budgetFit: "Within Budget",
          deadlinePressure: "Low",
          reasonsForFit: ["Near DC for internship access", "Affordable", "Strong government and policy programs"],
          topBlockers: [],
          nextActions: ["Submit application", "Research College Park Scholars program"],
        },
      ],
    },
  },
];

export const stageBadgeClasses: Record<StudentStage, string> = {
  "Early Builder": "bg-sky-100 text-sky-900",
  "Pre-Applicant": "bg-amber-100 text-amber-900",
  "Active Applicant": "bg-emerald-100 text-emerald-900",
};

export const confidenceBadgeClasses: Record<ConfidenceLevel, string> = {
  Low: "bg-amber-100 text-amber-900",
  Medium: "bg-sky-100 text-sky-900",
  High: "bg-emerald-100 text-emerald-900",
};

export const budgetBadgeClasses: Record<BudgetFit, string> = {
  "Within Budget": "bg-emerald-100 text-emerald-900",
  Stretch: "bg-amber-100 text-amber-900",
  "Over Budget": "bg-rose-100 text-rose-900",
};

export const dependenceBadgeClasses: Record<ScholarshipDependence, string> = {
  Low: "bg-emerald-100 text-emerald-900",
  Medium: "bg-amber-100 text-amber-900",
  High: "bg-rose-100 text-rose-900",
};

export const toneBadgeClasses: Record<"info" | "warning" | "success", string> = {
  info: "bg-sky-100 text-sky-900",
  warning: "bg-amber-100 text-amber-900",
  success: "bg-emerald-100 text-emerald-900",
};

export function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}

export function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(value));
}

export function getStudentById(id: string) {
  return students.find((student) => student.id === id);
}
