// apps/web/src/lib/dashboard-copy.ts
// Shared bilingual copy for the counselor dashboard.
// Keeps the UI labels centralised so language switching stays consistent across routes.
export type DashboardLanguage = "en" | "vi";

const en = {
  navLabel: "Navigation",
  navLeadQueue: "Lead Queue",
  navStudentProfile: "Student Profile",
  navBookingRequests: "Booking Requests",
  navSettings: "Settings",
  searchPlaceholder: "Search students, schools...",
  queueTitle: "Student Lead Queue",
  queueDescription: "Review pending consultation requests.",
  queueSearchPlaceholder: "Search by name or email...",
  queueStageFilter: "Filter by stage",
  queueAllStages: "All stages",
  queueColumns: {
    student: "Student",
    grade: "Grade",
    majors: "Major(s)",
    stage: "Stage",
    handoff: "Handoff",
    action: "Action",
  },
  queueReview: "Review profile",
  stageEarlyBuilder: "Early Builder",
  stagePreApplicant: "Pre-Applicant",
  stageActiveApplicant: "Active Applicant",
  detailBack: "Back to lead queue",
  detailContact: "Contact student",
  detailBooking: "Booking request",
  detailTopic: "Topic",
  detailTimeWindow: "Time window",
  detailAcademic: "Academic profile",
  detailHighSchool: "High school",
  detailCurriculum: "Curriculum",
  detailGpa: "GPA",
  detailMajors: "Intended major(s)",
  detailStrategy: "Strategy mode",
  detailActivities: "Activities & readiness",
  detailActivityDepth: "Activity depth",
  detailActivitiesLabel: "Activities",
  detailAwards: "Awards",
  detailLeadership: "Leadership",
  detailProjects: "Projects",
  detailEssays: "Essays",
  detailRecommendations: "Recommendations",
  detailDocuments: "Documents",
  detailBudget: "Budget & preferences",
  detailTargetBudget: "Target budget",
  detailStretchBudget: "Max stretch budget",
  detailScholarshipNeed: "Scholarship need",
  detailAffordability: "Affordability",
  detailGeography: "Geographic preferences",
  detailCampus: "Campus",
  detailAiSummary: "AI summary",
  detailRecommendationsTitle: "System recommendations",
  detailSchools: "Schools",
  detailCurrentOutlook: "Current outlook",
  detailProjectedOutlook: "Projected outlook",
  detailTuition: "Tuition / all-in",
  detailBudgetFit: "Budget fit",
  detailFitReasons: "Fit reasons",
  detailBlockers: "Top blockers",
  detailNextActions: "Next actions",
  detailVerified: "Last verified",
  detailSource: "Source",
  detailConfidence: "confidence",
  detailNotFound: "Student not found.",
  detailBackHome: "Back to queue",
  detailAcademicBand: "Academic",
  detailTestBand: "Test",
  settingsTitle: "Settings",
  settingsDescription: "Manage dashboard language, theme, notifications, and account details.",
  settingsLanguageTitle: "Language preferences",
  settingsThemeTitle: "Appearance",
  settingsNotificationsTitle: "Notification preferences",
  settingsAccountTitle: "Account & security",
  settingsLanguageLabel: "Interface language",
  settingsLanguageHelp: "Switch between English and Vietnamese instantly.",
  settingsThemeLabel: "Theme",
  settingsThemeHelp: "Use a light or dark canvas for long review sessions.",
  settingsNotificationsHelp: "Control which alerts you receive.",
  settingsAccountHelp: "Profile details for the current reviewer.",
  settingsLangEn: "English",
  settingsLangVi: "Tiếng Việt",
  settingsThemeLight: "Light",
  settingsThemeDark: "Dark",
  settingsNotifNewLeads: "New lead assignments",
  settingsNotifBooking: "Booking request updates",
  settingsNotifWeekly: "Weekly digest",
  settingsNotifSystem: "System alerts",
  settingsDisplayName: "Display name",
  settingsEmail: "Email address",
  settingsRole: "Role",
  settingsManaged: "Admin-managed",
  settingsSave: "Save changes",
  settingsSaved: "Saved",
  commonLight: "Light",
  commonDark: "Dark",
} as const;

const vi = {
  navLabel: "Điều hướng",
  navLeadQueue: "Danh sách học sinh",
  navStudentProfile: "Hồ sơ học sinh",
  navBookingRequests: "Yêu cầu đặt lịch",
  navSettings: "Cài đặt",
  searchPlaceholder: "Tìm học sinh, trường học...",
  queueTitle: "Danh sách học sinh chờ tư vấn",
  queueDescription: "Xem và xử lý các yêu cầu tư vấn đang chờ.",
  queueSearchPlaceholder: "Tìm theo tên hoặc email...",
  queueStageFilter: "Lọc theo giai đoạn",
  queueAllStages: "Tất cả giai đoạn",
  queueColumns: {
    student: "Học sinh",
    grade: "Lớp",
    majors: "Ngành",
    stage: "Giai đoạn",
    handoff: "Bàn giao",
    action: "Hành động",
  },
  queueReview: "Xem hồ sơ",
  stageEarlyBuilder: "Đang xây dựng",
  stagePreApplicant: "Chuẩn bị nộp",
  stageActiveApplicant: "Đang nộp",
  detailBack: "Quay lại danh sách",
  detailContact: "Liên hệ học sinh",
  detailBooking: "Yêu cầu đặt lịch",
  detailTopic: "Chủ đề",
  detailTimeWindow: "Khung giờ",
  detailAcademic: "Hồ sơ học thuật",
  detailHighSchool: "Trường THPT",
  detailCurriculum: "Chương trình",
  detailGpa: "GPA",
  detailMajors: "Ngành học dự kiến",
  detailStrategy: "Chiến lược",
  detailActivities: "Hoạt động & sẵn sàng",
  detailActivityDepth: "Độ sâu hoạt động",
  detailActivitiesLabel: "Hoạt động",
  detailAwards: "Giải thưởng",
  detailLeadership: "Lãnh đạo",
  detailProjects: "Dự án",
  detailEssays: "Bài luận",
  detailRecommendations: "Thư giới thiệu",
  detailDocuments: "Hồ sơ",
  detailBudget: "Ngân sách & ưu tiên",
  detailTargetBudget: "Ngân sách mục tiêu",
  detailStretchBudget: "Ngân sách tối đa",
  detailScholarshipNeed: "Nhu cầu học bổng",
  detailAffordability: "Độ nhạy chi phí",
  detailGeography: "Ưu tiên địa lý",
  detailCampus: "Khuôn viên",
  detailAiSummary: "Tóm tắt AI",
  detailRecommendationsTitle: "Gợi ý của hệ thống",
  detailSchools: "Trường",
  detailCurrentOutlook: "Triển vọng hiện tại",
  detailProjectedOutlook: "Triển vọng dự kiến",
  detailTuition: "Học phí / tổng chi phí",
  detailBudgetFit: "Phù hợp ngân sách",
  detailFitReasons: "Lý do phù hợp",
  detailBlockers: "Rào cản chính",
  detailNextActions: "Bước tiếp theo",
  detailVerified: "Cập nhật lần cuối",
  detailSource: "Nguồn",
  detailConfidence: "độ tin cậy",
  detailNotFound: "Không tìm thấy học sinh.",
  detailBackHome: "Quay lại danh sách",
  detailAcademicBand: "Học thuật",
  detailTestBand: "Kiểm tra",
  settingsTitle: "Cài đặt",
  settingsDescription: "Quản lý ngôn ngữ, giao diện, thông báo và thông tin tài khoản.",
  settingsLanguageTitle: "Tùy chọn ngôn ngữ",
  settingsThemeTitle: "Giao diện",
  settingsNotificationsTitle: "Tùy chọn thông báo",
  settingsAccountTitle: "Tài khoản & bảo mật",
  settingsLanguageLabel: "Ngôn ngữ giao diện",
  settingsLanguageHelp: "Chuyển đổi giữa tiếng Anh và tiếng Việt ngay lập tức.",
  settingsThemeLabel: "Chủ đề",
  settingsThemeHelp: "Dùng nền sáng hoặc tối cho các phiên xem dài.",
  settingsNotificationsHelp: "Kiểm soát loại cảnh báo bạn nhận được.",
  settingsAccountHelp: "Thông tin hồ sơ của người duyệt hiện tại.",
  settingsLangEn: "English",
  settingsLangVi: "Tiếng Việt",
  settingsThemeLight: "Sáng",
  settingsThemeDark: "Tối",
  settingsNotifNewLeads: "Phân công học sinh mới",
  settingsNotifBooking: "Cập nhật yêu cầu đặt lịch",
  settingsNotifWeekly: "Tóm tắt hàng tuần",
  settingsNotifSystem: "Cảnh báo hệ thống",
  settingsDisplayName: "Tên hiển thị",
  settingsEmail: "Địa chỉ email",
  settingsRole: "Vai trò",
  settingsManaged: "Quản lý bởi admin",
  settingsSave: "Lưu thay đổi",
  settingsSaved: "Đã lưu",
  commonLight: "Sáng",
  commonDark: "Tối",
} as const;

export const dashboardCopy = { en, vi } as const;
