// apps/web/src/lib/dashboard-extra-students.ts
// Additional seeded dashboard students split out to keep the main data module small.
// This preserves the same canonical dashboard data while respecting the repo line cap.
import type { StudentProfile } from "@/lib/dashboard-data";

export const extraStudents: StudentProfile[] = [
  {
    id: "4",
    name: "Dang Quynh Anh",
    email: "quynhanh.dang@gmail.com",
    phone: "+84 901 234 567",
    gradeLevel: 12,
    graduationYear: 2026,
    curriculum: "Vietnamese National + AP",
    gpa: "3.82 / 4.0",
    gradeTrend: "Upward",
    intendedMajors: ["International Relations", "Political Science"],
    highSchool: "Nguyen Hue High School",
    testScores: { toefl: "110", sat: "1460" },
    activities: "Model UN delegate, student ambassador, policy research intern.",
    awards: "Best Delegate at ASEAN MUN, National Essay Competition Winner.",
    leadership: "Secretary General of school MUN, youth advisory board member.",
    volunteering: "Youth policy advocacy group (150+ hrs).",
    projects: "Policy brief on Vietnam-US educational exchange.",
    essayStatus: "Final drafts complete.",
    recommendationLetters: "3 secured.",
    documentStatus: "All documents ready and submitted.",
    geographicPreferences: ["Washington DC area", "Northeast US"],
    campusType: "Urban",
    campusSize: "Medium",
    targetAnnualBudget: "$48,000",
    maxStretchBudget: "$55,000",
    scholarshipNeed: "Medium",
    strategyMode: "Aggressive ED2 consideration",
    studentStage: "Active Applicant",
    academicStrengthBand: "Strong",
    testReadinessBand: "Highly Competitive",
    activityDepthSignal: "Very strong policy and IR involvement.",
    leadershipSignal: "Very strong leadership with real civic experience.",
    scholarshipDependence: "Medium",
    affordabilitySensitivity: "Moderate",
    handoffDate: "2026-03-16",
    chatSummary: "Strong IR profile and deciding between ED2 and RD strategy.",
    recommendations: {
      reach: [{
        schoolName: "Georgetown University", city: "Washington", state: "DC",
        tuitionAnnualUsd: 65082, estimatedCostOfAttendanceUsd: 87000,
        scholarshipAvailabilityFlag: true, scholarshipNotes: "Need-based aid available",
        lastVerifiedAt: "2026-02-15", sourceUrls: ["https://finaid.georgetown.edu/"],
        tier: "Reach", currentOutlook: "Competitive", projectedOutlook: "Moderate-Strong",
        confidenceLevel: "Medium", budgetFit: "Over Budget", deadlinePressure: "High",
        reasonsForFit: ["Premier IR program", "DC internships", "Perfect essay fit"],
        topBlockers: ["Highly selective", "COA exceeds budget"],
        nextActions: ["Decide on ED2", "Complete financial aid file", "Polish essays"],
      }],
      target: [{
        schoolName: "George Washington University", city: "Washington", state: "DC",
        tuitionAnnualUsd: 63830, estimatedCostOfAttendanceUsd: 82000,
        scholarshipAvailabilityFlag: true, scholarshipNotes: "Presidential and merit scholarships up to full tuition",
        lastVerifiedAt: "2026-03-01", sourceUrls: ["https://financialaid.gwu.edu/"],
        tier: "Target", currentOutlook: "Good", projectedOutlook: "Strong",
        confidenceLevel: "High", budgetFit: "Stretch", deadlinePressure: "High",
        reasonsForFit: ["Strong IR school", "DC location", "Merit scholarship chances"], topBlockers: [],
        nextActions: ["Submit RD application", "Apply for Presidential scholarship"],
      }],
      safety: [{
        schoolName: "University of Maryland", city: "College Park", state: "MD",
        tuitionAnnualUsd: 40306, estimatedCostOfAttendanceUsd: 56000,
        scholarshipAvailabilityFlag: true, scholarshipNotes: "International merit scholarships available",
        lastVerifiedAt: "2026-03-08", sourceUrls: ["https://financialaid.umd.edu/"],
        tier: "Safety", currentOutlook: "Strong", projectedOutlook: "Very Strong",
        confidenceLevel: "High", budgetFit: "Within Budget", deadlinePressure: "Low",
        reasonsForFit: ["Near DC for internships", "Affordable", "Strong policy programs"], topBlockers: [],
        nextActions: ["Submit application", "Research scholars program"],
      }],
    },
  },
];
